version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ChatApp.Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=ChatApp;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - ConnectionStrings__AzureSignalR=${AZURE_SIGNALR_CONNECTION_STRING}
      - CognitiveServices__TextAnalyticsEndpoint=${COGNITIVE_SERVICES_ENDPOINT}
      - CognitiveServices__TextAnalyticsKey=${COGNITIVE_SERVICES_KEY}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    ports:
      - "5000:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./chat-app-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: 